// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwensonHE.Store.DatabaseContext;

namespace SwensonHE.Store.Presistance.Migrations
{
    [DbContext(typeof(StoreDBEntities))]
    [Migration("20210129160641_AddStoreIntialMigration")]
    partial class AddStoreIntialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.Flavor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Flavor");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.ItemSKU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FlavorID")
                        .HasColumnType("int");

                    b.Property<bool>("HasWaterCompatibality")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemSizeID")
                        .HasColumnType("int");

                    b.Property<int?>("ModelTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("PackID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("FlavorID");

                    b.HasIndex("ItemSizeID");

                    b.HasIndex("ModelTypeID");

                    b.HasIndex("PackID");

                    b.HasIndex("ProductID");

                    b.ToTable("ItemSKU");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.ItemSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ItemSize");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.ModelType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("ModelType");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.Pack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dozen")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Pack");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.HasIndex("ProductTypeID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.ProductType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.ItemSKU", b =>
                {
                    b.HasOne("SwensonHE.Store.Data.Entities.Flavor", "Flavor")
                        .WithMany("itemSKUs")
                        .HasForeignKey("FlavorID");

                    b.HasOne("SwensonHE.Store.Data.Entities.ItemSize", "ItemSize")
                        .WithMany("itemSKUs")
                        .HasForeignKey("ItemSizeID");

                    b.HasOne("SwensonHE.Store.Data.Entities.ModelType", "ModelType")
                        .WithMany("itemSKUs")
                        .HasForeignKey("ModelTypeID");

                    b.HasOne("SwensonHE.Store.Data.Entities.Pack", "Pack")
                        .WithMany("itemSKUs")
                        .HasForeignKey("PackID");

                    b.HasOne("SwensonHE.Store.Data.Entities.Product", "Product")
                        .WithMany("itemSKUs")
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("SwensonHE.Store.Data.Entities.Product", b =>
                {
                    b.HasOne("SwensonHE.Store.Data.Entities.Item", "Item")
                        .WithMany("Products")
                        .HasForeignKey("ItemID");

                    b.HasOne("SwensonHE.Store.Data.Entities.ProductType", "ProductType")
                        .WithMany("products")
                        .HasForeignKey("ProductTypeID");
                });
#pragma warning restore 612, 618
        }
    }
}
